# Generated by Django 6.0.3 on 2026-04-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('conteudo', models.TextField()),
                ('data', models.DateField()),
                ('imagem', models.ImageField(blank=True, upload_to='artigos/')),
                ('legenda_imagem', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MembroEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, upload_to='equipe/')),
            ],
        ),
    ]
