# Generated by Django 6.0.3 on 2026-04-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restauranteapolo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='autor',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
    ]
