# Generated by Django 6.0.3 on 2026-04-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100)),
                ('data_reserva', models.DateField()),
                ('hora_reserva', models.TimeField()),
                ('numero_pessoas', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('C', 'Confirmada'), ('X', 'Cancelada')], default='P', max_length=1)),
            ],
        ),
    ]
